/*
======================================================
QUESTION 01
Business Question:
What is the total revenue generated by the company?
======================================================
*/

SELECT
    ROUND(SUM(payment_value), 2) AS total_revenue
FROM order_payments;

-- Business Insight:
-- Measures the overall revenue generated from all completed payments.

/*
======================================================
QUESTION 02
Business Question:
How many orders have been placed?
======================================================
*/

SELECT
    COUNT(*) AS total_orders
FROM orders;

-- Business Insight:
-- Total number of orders registered in the platform.

/*
======================================================
QUESTION 03
Business Question:
What is the average order value?
======================================================
*/

SELECT
    ROUND(AVG(payment_value), 2) AS average_order_value
FROM order_payments;

-- Business Insight:
-- Average amount paid per order.

/*
======================================================
QUESTION 04
Business Question:
How many unique customers are there?
======================================================
*/

SELECT
    COUNT(DISTINCT customer_unique_id) AS total_customers
FROM customers;

-- Business Insight:
-- Measures the size of the customer base.

/*
======================================================
QUESTION 05
Business Question:
How many sellers operate in the marketplace?
======================================================
*/

SELECT
    COUNT(*) AS total_sellers
FROM sellers;

-- Business Insight:
-- Total number of registered sellers.

/*
======================================================
QUESTION 06
Business Question:
How many products are available?
======================================================
*/

SELECT
    COUNT(*) AS total_products
FROM products;

-- Business Insight:
-- Total products listed in the catalog.

/*
======================================================
QUESTION 07
Business Question:
Which months generate the highest revenue?
======================================================
*/

SELECT
    TO_CHAR(
        DATE_TRUNC('month', o.order_purchase_timestamp),
        'YYYY-MM'
    ) AS month,

    ROUND(
        SUM(op.payment_value),
        2
    ) AS revenue
FROM orders o
INNER JOIN order_payments op
ON o.order_id = op.order_id

GROUP BY month
ORDER BY revenue DESC;

-- Business Insight:
-- Helps identify seasonal sales peaks.


/*
======================================================
QUESTION 08
Business Question:
Which states generate the highest revenue?
======================================================
*/

SELECT
    c.customer_state,
    ROUND(
        SUM(op.payment_value),
        2
    ) AS revenue
FROM customers c
INNER JOIN orders o
ON c.customer_id=o.customer_id
INNER JOIN order_payments op
ON o.order_id=op.order_id

GROUP BY c.customer_state
ORDER BY revenue DESC;

-- Business Insight:
-- Shows the most profitable regions.


/*
======================================================
QUESTION 09
Business Question:
Which product categories generate the highest revenue?
======================================================
*/

SELECT
    p.product_category_name,
    ROUND(
        SUM(oi.price),
        2
    ) AS revenue
FROM products p
INNER JOIN order_items oi
ON p.product_id=oi.product_id

GROUP BY p.product_category_name
ORDER BY revenue DESC;

-- Business Insight:
-- Identifies top-performing product categories.

/*
======================================================
QUESTION 10
Business Question:
Which sellers generate the highest revenue?
======================================================
*/

SELECT
    seller_id,
    ROUND(
        SUM(price),
        2
    ) AS revenue,
    RANK() OVER(
        ORDER BY SUM(price) DESC
    ) AS seller_rank
FROM order_items
GROUP BY seller_id
ORDER BY seller_rank
LIMIT 10;

-- Business Insight:
-- Top revenue-generating sellers.

/*
======================================================
QUESTION 11
Business Question:
Which states have the highest number of customers?
======================================================
*/

SELECT
    customer_state,

    COUNT(*) AS customers
FROM customers

GROUP BY customer_state
ORDER BY customers DESC;


/*
======================================================
QUESTION 12
Business Question:
Which customers spend the most?
======================================================
*/

SELECT
    c.customer_unique_id,
    ROUND(
        SUM(op.payment_value),
        2
    ) AS revenue
FROM customers c
INNER JOIN orders o
ON c.customer_id=o.customer_id
INNER JOIN order_payments op
ON o.order_id=op.order_id

GROUP BY c.customer_unique_id
ORDER BY revenue DESC
LIMIT 20;


/*
======================================================
QUESTION 13
Business Question:
What is the average delivery time?
======================================================
*/

SELECT
    ROUND(
        AVG(
            order_delivered_customer_date -
            order_purchase_timestamp
        ),
        2
    ) AS average_delivery_time
FROM orders

WHERE order_delivered_customer_date IS NOT NULL;


/*
======================================================
QUESTION 14
Business Question:
Which states experience the longest delivery times?
======================================================
*/

SELECT
    c.customer_state,
    ROUND(
        AVG(
            o.order_delivered_customer_date -
            o.order_purchase_timestamp
        ),
        2
    ) AS avg_delivery_time
FROM customers c
INNER JOIN orders o
ON c.customer_id=o.customer_id

WHERE o.order_delivered_customer_date IS NOT NULL
GROUP BY c.customer_state
ORDER BY avg_delivery_time DESC;


/*
======================================================
QUESTION 15
Business Question:
Which product categories have the best ratings?
======================================================
*/

SELECT
    p.product_category_name,
    ROUND(
        AVG(r.review_score),
        2
    ) AS average_score,
    COUNT(DISTINCT r.review_id) AS reviews
FROM products p
INNER JOIN order_items oi
ON p.product_id=oi.product_id
INNER JOIN order_reviews r
ON oi.order_id=r.order_id

GROUP BY p.product_category_name
HAVING COUNT(DISTINCT r.review_id)>=100
ORDER BY average_score DESC;


/*
======================================================
QUESTION 16
Business Question:
Which sellers have the highest average order value?
======================================================

Expected Output:
- seller_id
- average_order_value
- total_orders

Business Insight:
Identify sellers that generate higher-value orders on average.
*/
SELECT
    seller_id,
    ROUND(
        AVG(order_value),
        2
    ) AS average_order_value,
    COUNT(*) AS total_orders
FROM (
    SELECT
        seller_id,
        order_id,
        SUM(price) AS order_value
    FROM order_items
    GROUP BY
        seller_id,
        order_id

) seller_orders
GROUP BY seller_id
ORDER BY average_order_value DESC
LIMIT 10;

/*
======================================================
QUESTION 17
Business Question:
Which payment methods generate the highest revenue?
======================================================

Expected Output:
- payment_type
- total_revenue
- total_payments

Business Insight:
Understand customer payment preferences and their contribution to revenue.
*/
SELECT
    payment_type,
    ROUND(
        SUM(payment_value),
        2
    ) AS total_revenue,
    COUNT(*) AS total_payments
FROM order_payments
GROUP BY payment_type
ORDER BY total_revenue DESC;


/*
======================================================
QUESTION 18
Business Question:
Which payment methods have the highest average transaction value?
======================================================

Expected Output:
- payment_type
- average_payment
- total_transactions

Business Insight:
Some payment methods may be associated with larger purchases.
*/

SELECT
    payment_type,
    ROUND(
        AVG(payment_value),
        2
    ) AS average_payment,
    COUNT(*) AS total_transactions
FROM order_payments
GROUP BY payment_type
ORDER BY average_payment DESC;


/*
======================================================
QUESTION 19
Business Question:
Which product categories sell the largest number of items?
======================================================

Expected Output:
- product_category_name
- total_items_sold

Business Insight:
Measures product popularity independently of revenue.
*/
SELECT
    p.product_category_name,
    COUNT(*) AS total_items_sold
FROM products p
INNER JOIN order_items oi
ON p.product_id=oi.product_id
GROUP BY p.product_category_name
ORDER BY total_items_sold DESC
LIMIT 10;

/*
======================================================
QUESTION 20
Business Question:
Which sellers have sold the highest number of products?
======================================================

Expected Output:
- seller_id
- total_products_sold

Business Insight:
Identify the most active sellers in the marketplace.
*/
SELECT
    seller_id,
    COUNT(*) AS total_products_sold
FROM order_items
GROUP BY seller_id
ORDER BY total_products_sold DESC;

/*
======================================================
QUESTION 21
Business Question:
Which orders contain the highest number of items?
======================================================

Expected Output:
- order_id
- total_items

Business Insight:
Large orders often represent valuable customers.
*/
SELECT
    order_id,
    COUNT(*) AS total_items
FROM order_items
GROUP BY order_id
ORDER BY total_items DESC
LIMIT 10;

/*
======================================================
QUESTION 22
Business Question:
Which states have the highest average order value?
======================================================

Expected Output:
- customer_state
- average_order_value
- total_orders

Business Insight:
Identify regions where customers spend more per purchase.
*/
--  Metodo 1
SELECT
    customer_state,
    ROUND(
        AVG(order_value),
        2
    ) AS average_order_value,
    COUNT(*) AS total_orders
FROM (
    SELECT
        o.order_id,
        c.customer_state,
        SUM(op.payment_value) AS order_value
    FROM customers c
    INNER JOIN orders o
        ON c.customer_id = o.customer_id
    INNER JOIN order_payments op
        ON o.order_id = op.order_id
    GROUP BY
        o.order_id,
        c.customer_state
) state_orders
GROUP BY customer_state
ORDER BY average_order_value DESC;

-- Metodo 2

WITH state_orders AS (
    SELECT
        o.order_id,
        c.customer_state,
        SUM(op.payment_value) AS order_value
    FROM customers c
    INNER JOIN orders o
        ON c.customer_id = o.customer_id
    INNER JOIN order_payments op
        ON o.order_id = op.order_id
    GROUP BY
        o.order_id,
        c.customer_state
)
SELECT
    customer_state,
    ROUND(
        AVG(order_value),
        2
    ) AS average_order_value,
    COUNT(*) AS total_orders
FROM state_orders
GROUP BY customer_state
ORDER BY average_order_value DESC;

/*
======================================================
QUESTION 23
Business Question:
Which product categories have the highest average selling price?
======================================================

Expected Output:
- product_category_name
- average_price

Business Insight:
Shows premium product categories.
*/
SELECT
    p.product_category_name,
    ROUND(
        AVG(oi.price),
        2
    ) AS average_price
FROM products p
INNER JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_category_name
ORDER BY average_price DESC;


/*
======================================================
QUESTION 24
Business Question:
How many orders were delivered late?
======================================================

Expected Output:
- delayed_orders

Business Insight:
Measure logistics performance.
*/
SELECT
    COUNT(*) AS delayed_orders
FROM orders
WHERE
    order_status='delivered'
    AND order_delivered_customer_date >
        order_estimated_delivery_date;


/*
======================================================
QUESTION 25
Business Question:
Which states have the highest percentage of delayed deliveries?
======================================================

Expected Output:
- customer_state
- delayed_orders
- total_orders
- delay_percentage

Business Insight:
Identify regions where logistics need improvement.
*/
SELECT
    c.customer_state,
    COUNT(*) FILTER (
        WHERE
            o.order_status='delivered'
            AND
            o.order_delivered_customer_date >
            o.order_estimated_delivery_date
    ) AS delayed_orders,
    COUNT(*) AS total_orders,
    ROUND(
        COUNT(*) FILTER (
            WHERE
                o.order_status='delivered'
                AND
                o.order_delivered_customer_date >
                o.order_estimated_delivery_date
        )::NUMERIC / COUNT(*) *100, 2
    ) AS delay_percentage
FROM customers c
INNER JOIN orders o
ON c.customer_id=o.customer_id
GROUP BY c.customer_state
ORDER BY delay_percentage DESC;


/*
======================================================
QUESTION 26
Business Question:
What are the Top 10 customers by lifetime value?
======================================================
*/
SELECT
    c.customer_unique_id,
    ROUND(
        SUM(op.payment_value),
        2
    ) AS lifetime_value,
    COUNT(DISTINCT o.order_id) AS total_orders
FROM customers c
INNER JOIN orders o 
    ON c.customer_id = o.customer_id
INNER JOIN order_payments op
    ON o.order_id = op.order_id
GROUP BY c.customer_unique_id
ORDER BY lifetime_value DESC
LIMIT 10;

/*
======================================================
QUESTION 27
Business Question:
Which sellers have the best review score?
======================================================
*/
SELECT
    s.seller_id,
    ROUND(
        AVG(r.review_score),
        2
    ) AS average_review_score,
    COUNT(DISTINCT r.review_id) AS total_reviews
FROM sellers s
INNER JOIN order_items oi
    ON s.seller_id = oi.seller_id
INNER JOIN order_reviews r
    ON oi.order_id = r.order_id
GROUP BY s.seller_id
ORDER BY average_review_score DESC
LIMIT 10;

/*
======================================================
QUESTION 28
Business Question:
Is there a relationship between delivery time and review score?
======================================================
*/
SELECT
    ROUND(
        AVG(order_delivered_customer_date - order_purchase_timestamp), 2
    ) AS average_delivery_days,
    review_score,
    COUNT(*) AS total_orders
FROM orders o
INNER JOIN order_reviews r
ON o.order_id=r.order_id
WHERE
    order_delivered_customer_date IS NOT NULL
GROUP BY review_score
ORDER BY review_score;


/*
======================================================
QUESTION 29
Business Question:
Which month has the highest average order value?
======================================================
*/
SELECT
    month,
    ROUND(AVG(order_value), 2) AS average_order_value
FROM(
    SELECT
        DATE_TRUNC(
            'month',
            o.order_purchase_timestamp
        ) AS month,
        o.order_id,
        SUM(op.payment_value) AS order_value
    FROM orders o
    INNER JOIN order_payments op
    ON o.order_id=op.order_id
    GROUP BY
        month,
        o.order_id
) t
GROUP BY month
ORDER BY average_order_value DESC
LIMIT 1;

/*
======================================================
QUESTION 30
Business Question:
Which categories generate high revenue but low customer satisfaction?
======================================================
*/

SELECT
    p.product_category_name,
    ROUND(SUM(oi.price), 2) AS revenue,
    ROUND(AVG(r.review_score), 2) AS average_review
FROM products p
INNER JOIN order_items oi
ON p.product_id=oi.product_id
INNER JOIN order_reviews r
ON oi.order_id=r.order_id
GROUP BY p.product_category_name
ORDER BY
    revenue DESC,
    average_review ASC;